### ISSUE TITLE
Ontology loading is broken on PHI-Canto

### ISSUE THREAD

**Issue by jseager7** [pombase/canto#2288]
@kimrutherford The nightly ontology reload script that we use for PHI-Canto has been failing with the following error:

```
/usr/local/bin/owltools: 3: /usr/local/bin/owltools: Syntax error: redirection unexpected
"owltools http://snapshot.geneontology.org/ontology/go-basic.obo --save-closure-for-chado /tmp/HBChIS752t" unexpectedly returned ex$ at lib/Canto/Config/ExtensionProcess.pm line 59
        (in cleanup) Canto::Track::OntologyLoad::finalise() not called
```

I'm not sure when this started happening, because we still don't have email alerts set up for when the ontology loading fails, but I suspect it's related to the recent upgrade of the Docker image, since we call our reload script through `canto_docker`:

```sh
./canto/script/canto_docker --non-interactive ./script/canto_load.pl \
--process-extension-config \
--ontology https://curation.pombase.org/ontologies/PSI-MOD-2016-01-19.obo \
--ontology http://snapshot.geneontology.org/ontology/go-basic.obo \
# etc...
```

**Comment by kimrutherford** [comment]
Sorry about that James.  When the base Docker image is created it downloads the latest owltools.  I didn't notice that the downloaded owltools (`/usr/local/bin/owltools` in the image) is corrupted.  I've create an owltools issue about the download: https://github.com/owlcollab/owltools/issues/301

I'll see if I can work around the problem.

For the record here's a sample of the current contents of the current `/usr/local/bin/owltools`:

```
  <!DOCTYPE html><html class=""><head resURL="/static/1ae9584c" data-rooturl="" data-resurl="/static/1ae9584c">
    

    <title>Jenkins</title><link rel="stylesheet" href="/static/1ae9584c/jsbundles/base-styles-v2.css" type="text/css"><link rel="stylesheet" 

...

Caused: org.jvnet.hudson.reactor.ReactorException
        at org.jvnet.hudson.reactor.Reactor.execute(Reactor.java:282)
        at jenkins.InitReactorRunner.run(InitReactorRunner.java:50)
        at jenkins.model.Jenkins.executeReactor(Jenkins.java:1166)
        at jenkins.model.Jenkins.&lt;init>(Jenkins.java:966)
        at hudson.model.Hudson.&lt;init>(Hudson.java:85)
        at hudson.model.Hudson.&lt;init>(Hudson.java:81)
        at hudson.WebAppMain$3.run(WebAppMain.java:233)
Caused: hudson.util.HudsonFailedToLoad
        at hudson.WebAppMain$3.run(WebAppMain.java:250)
</pre></div></div><footer><div class="container-fluid"><div class="row"><div class="col-md-6" id="footer"></div><div class="col-md-18"><span class="page_generated">Page generated: May 14, 2020 10:39:30 PM PDT</span><span class="jenkins_ver"><a href="https://jenkins.io/">Jenkins ver. 2.222.1</a></span></div></div></div></footer><script async="true" src="/static/1ae9584c/scripts/svgxuse.min.js" type="text/javascript"></script></body></html>
```

**Comment by kimrutherford** [comment]
I've manually updated the Docker image using the latest owltools release:
https://github.com/owlcollab/owltools/releases/tag/2020-04-06

Could you close this issue if it's working?

**Comment by jseager7** [comment]
This has fixed the ontology loading being broken, thanks, but for some reason OWLTools is trying to parse the response content of OBOLibrary PURLs, rather than the ontology files they redirect to:

```
Parser: org.semanticweb.owlapi.oboformat.OBOFormatOWLAPIParser@3fc9dfc5
    Stack trace:
LINENO: 1 - Could not find tag separator ':' in line.
LINE: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">      
```

I confirmed this using cURL on the PURL for PHIPO:
```
> curl http://purl.obolibrary.org/obo/phipo/phipo-simple.obo
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://raw.githubusercontent.com/PHI-base/phipo/master/phipo-simple.obo">here</a>.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at purl.obolibrary.org Port 80</address>
</body></html>
```
I don't know whether this is due to OWLTools or something else in the script. It's possible that we might have had this problem before, a long time in the past. Anyway, we can't load PHIPO or SO using the PURLs for the time being. For now, I can just switch them back to using their addresses on `raw.githubusercontent.com`, but that's obviously more brittle than using PURLs for ontologies that we don't control.

**Comment by kimrutherford** [comment]
> don't know whether this is due to OWLTools or something else in the script.

I think it's an OWLTools problem.  I tried a few owtools commands with OBO files outside of the container and I get the same problem.  Oddly it works fine with `.owl` files.  I'm building a new base image with the older owltools and I'll file a bug report.

**Comment by kimrutherford** [comment]
Bug report filed: https://github.com/owlcollab/owltools/issues/302

I've pushed a new base image ([v12](https://hub.docker.com/layers/pombase/canto-base/v12/images/sha256-e498f3178f41a4104b4d921faaf947fdc82729da7676ba573015e68ca5d4c44b?context=repo)) which is the same except for reverting to the owltools executable from the older, working image.

Could you let me know how you get on?  Sorry this has been a hassle.

**Comment by jseager7** [comment]
Thanks for your help fixing this. I'm running the ontology reload again now, and while it's not finished yet, it seems like it's passed the previous point of error with no problems. It's not a massive hassle if the PURLs break because they tend to be easy to dereference to some other mostly-persistent URL, like GitHub. It hasn't held up any curation either.

**Comment by kimrutherford** [comment]
I'll leave this issue open until owltools is fixed.  Then I'll try again to update to the latest version.

**Comment by jseager7** [comment]
Just to confirm, the ontology loading finished with no problems on the demo server.
